---
- name: Manage Docker container and image
  hosts: slave
  user: root
  become: yes
  gather_facts: no
  connection: ssh

  vars:
    ansible_python_interpreter: /usr/bin/python3
    container_name: first_container
    image_name: subhabrata3002/devops_project_freestyle_1:latest

  tasks:
    - name: Update package cache (ensure Python 3's dnf module is used)
      package:
        name: '*'
        state: latest
      # Uncomment the appropriate when condition based on your target hosts' OS.
      # when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      when: ansible_pkg_mgr == 'dnf'
      
    - name: Install Git
      package:
        name: git
        state: present
      
    - name: Clone the GitHub repository
      git:
        repo: https://github.com/Subhabrata2468/project1.git
        dest: /app

    - name: Copy website contents to Nginx's HTML directory
      copy:
        src: /app/
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Start Nginx container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "9000:80"
        volumes:
          - /usr/share/nginx/html:/usr/share/nginx/html
        state: started
