---
- name: Manage Docker container and image
  hosts: slave
  user: root
  become: yes
  gather_facts: yes
  connection: ssh

  vars:
    ansible_python_interpreter: /usr/bin/python3
    container_name: first_container
    image_name: subhabrata3002/devops_project_freestyle_1:latest

  tasks:
    - name: Start Nginx container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "9000:80"
        volumes:
          - /usr/share/nginx/html:/usr/share/nginx/html
        state: started
